lesson 1 task 1
antdolg1/jg_java_1_monday_june_2022 pull request #13
Opened 2022-06-30 14:49 UTC by Leonards205

2022-07-02 16:03 UTC, antdolg1 commented on src/main/java/students/student_leonards_petkevics/leosson_1/TaskEleven.java
> +        System.out.println(a/b);
Не забываем про пробелы. Давайте сразу привыкать оформлять код красиво, чтобы его было легче читать.
System.out.println(a / b);

2022-07-02 16:04 UTC, antdolg1 commented on src/main/java/students/student_leonards_petkevics/leosson_1/TaskEleven.java
> +public class TaskEleven {
Давайте задания называть как и в папке homework - Task_11 или Task11.

2022-07-02 16:05 UTC, antdolg1 commented on src/main/java/students/student_leonards_petkevics/leosson_1/tasktwelve.java
> +public class tasktwelve {
public class Task_12 {

2022-07-02 16:06 UTC, antdolg1 commented on src/main/java/students/student_leonards_petkevics/lesson_2/task1.java
> +
Зачем столько пустых строчек?

2022-07-02 16:06 UTC, antdolg1 commented on src/main/java/students/student_leonards_petkevics/lesson_2/task1.java
> +        System.out.print("Answer is: "+secondnumber);
```suggestion
        System.out.print("Answer is: " + secondnumber);
```

2022-07-02 16:06 UTC, antdolg1 commented on src/main/java/students/student_leonards_petkevics/lesson_2/task1.java
> +        int firstnumber;
```suggestion
        int firstNumber;
```
В названиях переменных мы использует стиль camelCase

2022-07-02 16:06 UTC, antdolg1 commented on src/main/java/students/student_leonards_petkevics/lesson_2/task1.java
> +        int secondnumber;
Тут тоже самое.

2022-07-02 16:08 UTC, antdolg1 commented on src/main/java/students/student_leonards_petkevics/lesson_2/task1.java
> +        secondnumber = firstnumber-(secondnumber );
Почему вы решили переопределить переменную а не создать новую (например с названием result)?

2022-07-02 16:12 UTC, antdolg1 requested changes
Оставил пару комментариев по первым заданиям. В целом во всех заданиях одинаковые недочёты. Где-то форматированние кода, где-то неправильно название переменных. Пробегитесь по заданиям и исправьте пожалуйста. Так же давайте немного подкорректируем структуру папок. Она должна быть точно такой как в папке teacher/lesson_i/homework.

2022-07-03 19:46 UTC, Leonards205 commented on src/main/java/students/student_leonards_petkevics/lesson_2/task1.java
> +        secondnumber = firstnumber-(secondnumber );
у меня просто по другому не получалась.

2022-07-29 12:17 UTC, closed without merging