Student Nikita Bondars lesson 1
antdolg1/jg_java_1_monday_june_2022 pull request #3
Opened 2022-06-27 15:47 UTC by NickBRiga

Created 1st homework

2022-07-01 08:38 UTC, antdolg1 commented on src/main/java/students/student_Nikita_Bondars/Lesson_1/Task_12.java
> +}
Please format line 12 and 13

```
    }
}
```

2022-07-01 08:40 UTC, antdolg1 requested changes
Please try to use english when outputting text to console and adding comments. It will help you in future.

2022-07-02 20:01 UTC, NickBRiga commented on src/main/java/students/student_Nikita_Bondars/Lesson_1/Task_11.java
> +    public static void main(final String[] args)  {
Fixed

2022-07-02 20:02 UTC, NickBRiga commented on src/main/java/students/student_Nikita_Bondars/LessonWork2/Variables.java
> +        System.out.println("myDouble value is: " + myDouble );
Fixed

2022-07-04 19:18 UTC, antdolg1 approved these changes
All good

2022-07-04 19:18 UTC, merged