Lesson_3_level_7
antdolg1/jg_java_1_monday_june_2022 pull request #36
Opened 2022-07-08 20:06 UTC by AlisaSin

2022-07-12 10:53 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/BottleOfWine.java
> +    String collor;
я переключаюсь на ветку этого задания но в ней нет этого класса, где мне его искать, чтобы исправить?

2022-07-17 12:29 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/BottleOfWine.java
> +    String collor;
Только что проверил, всё доступно в ветке `alisa-sinavska-lesson3-level7`
<img width="877" alt="image" src="https://user-images.githubusercontent.com/47293463/179398342-be2ae58b-c7cf-421b-b465-d186576cfa6e.png">

2022-07-17 12:30 UTC, antdolg1 requested changes
Please check comment.

2022-07-24 11:55 UTC, antdolg1 approved these changes
Now all is good!

2022-07-24 14:33 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/BottleOfWineDemo.java
> +        bottleOfWine.drinking(); // а как в данном случае можно сделать чтобы не было новой строчки?
Use `System.out.print` instead of `System.out.println` in `drinking()` method.

2022-07-24 14:35 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/ComputerDemo.java
> +        String manufacturer = dell.getManufacturer();
Your method `getManufacturer()` does not return any value, it just outputs some text to the console.

2022-07-24 14:35 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Computer.java
> +
Please fix formatting.

2022-07-24 14:37 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Cirkle.java
> +public class Cirkle {
Cirkle --> Circle

2022-07-24 14:40 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Cirkle.java
> +    void calculateArea() {System.out.println(radius * Math.PI);
This is not what was required in the task. You need to create method which will return calculated area of the circle (see below). Also there is no need to create constructor which will set radius 5 as default in real world this is confusing and might lead to problems. Please fix.

_"Разработать класс - круг, у которого должны быть следующие характеристики:
Свойства: радиус (double radius),
Методы: расчет площади (double calculateArea()).

Класс с объявлением фигуры круг должен называться "Circle".
Класс с демонстрацией работы должен называться "CircleDemo"."_

2022-07-24 14:44 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/CatDemo.java
> +        //пыталась сделать так, что в классе Cat: public Cat(name), а в CatDemo имя писать в Cat cat = new Cat(Misha), но тогда при таком же system.ot.. не работает. Почему?
You need to create constructor which will take name a parameter.

2022-07-24 14:47 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Product.java
> +        this.name = "cucumber";
Why you hardcoded "cucumber" as a name value for this constructor? I would suggest to create constructor with all three parameters instead.

2022-07-24 14:49 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/ProductDemo.java
> +        product.actualPrice();
Result would look like this:
```
cucumber actual price is:
53.33
```
Is it planned like this or you want to output it in a one line?

2022-07-24 14:52 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Product.java
> +}
That's not what was required in the task:
```
1. Расчет актуальной стоимости с учетом скидки (double actualPrice()).
2. Вывод информации о продукте в консоль (void printInformation()).
3. Название продукта нужно задавать через конструктор.
4. Стоимость и скидку нужно задавать через соответствующие методы.
```
Please double check the task. Feel free to ask questions if something is unclear.

2022-07-24 14:54 UTC, antdolg1 requested changes
Please check comments. There are few things what needs to be fixed/refactored.

2022-07-26 12:14 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/CatDemo.java
> +        //пыталась сделать так, что в классе Cat: public Cat(name), а в CatDemo имя писать в Cat cat = new Cat(Misha), но тогда при таком же system.ot.. не работает. Почему?
поменяла

2022-07-26 12:14 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Cirkle.java
> +    void calculateArea() {System.out.println(radius * Math.PI);
сделала

2022-07-26 12:15 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Cirkle.java
> +public class Cirkle {
исправила

2022-07-26 12:15 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Computer.java
> +
есть

2022-07-26 12:15 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/ComputerDemo.java
> +        String manufacturer = dell.getManufacturer();
вроде исправила, если правильно поняла

2022-07-26 12:15 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/BottleOfWineDemo.java
> +        bottleOfWine.drinking(); // а как в данном случае можно сделать чтобы не было новой строчки?
спасибо

2022-07-26 12:19 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/ProductDemo.java
> +        product.actualPrice();
я так сделала, так как не знаю как иначе. В одну строчку у меня не получилось. Метод не получается написать в скобках system.out.println

2022-07-26 12:23 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/ProductDemo.java
> +        product.actualPrice();
все получилось

2022-07-26 12:30 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Product.java
> +}
Исправила, посмотрите, правильно ли поняла?

2022-07-28 10:42 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Computer.java
> +
Still not formatted properly. This is what you have:
![image](https://user-images.githubusercontent.com/47293463/181486609-297258e1-4a98-4b52-83d1-a483a4bc42df.png)

And this how it should look like:
![image](https://user-images.githubusercontent.com/47293463/181486693-b18e989f-4afe-47d4-a937-16acb1137811.png)

2022-07-28 10:50 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/Product.java
> +}
- [ ] Расчет актуальной стоимости с учетом скидки (double actualPrice())
- [ ] Вывод информации о продукте в консоль (void printInformation())
- [ ] Название продукта нужно задавать через конструктор
- [ ] Стоимость и скидку нужно задавать через соответствующие методы

2022-07-28 11:08 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/_lesson_3/level_2/level_7/CatDemo.java
> +                " "); // строку пропустить можно только так или есть по красивее способ?
You can skip line by just using `System.out.println();`

2022-07-28 11:10 UTC, antdolg1 requested changes
Overall you are going in a right direction but still there are few things to fix. Please check my comments for the task 31.

2022-08-01 21:29 UTC, antdolg1 approved these changes
I will approve and merge the branch so it does not hang here. In level 7 all tasks except task 31 are done. Good job Alisa!

2022-08-01 21:29 UTC, merged