St robert pavlov lesson 3 level 1 task 1 2 3 4 5 6
antdolg1/jg_java_1_monday_june_2022 pull request #37
Opened 2022-07-10 08:02 UTC by roberts-pavlovs

2022-07-15 15:59 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_1/Task_12_lesson_1_homework.java
> +        System.out.println(" Result " + result);
Redundant whitespace before 'Result'

2022-07-15 16:04 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_3/App.java
> +        Dog yourDog = new Dog(age:2, name:"John", height: 30);
Please remove `age:` , `name:` , `height:`. These words are shown by Intellij IDEA as a hit for you so you know what parameters should be passed to constructor.

2022-07-15 16:08 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_3/Lesson_3Task_9.java
> +
According to the task you need to read text from console, for that we use `nextLine()` method. Method `nextInt()` is used to read number. Also you need to print out that name to console. Please double check Task_9 description.

2022-07-15 16:13 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_3/Task_1/Robot.java
> +
Please format methods `sayYourName()` and `sayYourName2()` and also remove redundant empty lines.

_Hint: you can use shortkey **Ctrl+Alt+L** for autoformatting._

2022-07-15 16:13 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_3/Task_1/Task_2/Robot.java
> +
Please format code.

2022-07-15 16:17 UTC, antdolg1 requested changes
Please take a look at comments, checkout to the branch `st-robert-pavlov-lesson-3-level-1-task-1-2-3-4-5-6` fix mentioned issues, commit and push changes to branch `st-robert-pavlov-lesson-3-level-1-task-1-2-3-4-5-6` and re-request review for the pull request.

2022-08-02 18:25 UTC, roberts-pavlovs commented on src/main/java/students/student_robert_pavlov/homework/lesson_3/Lesson_3Task_9.java
> +
Прошу прощения, исправил ошибки, но не знаю как запросить новый ревью?

2022-08-02 20:36 UTC, antdolg1 submitted a review, later dismissed
Now its good!

2022-08-02 20:41 UTC, antdolg1 approved these changes

2022-08-02 20:41 UTC, merged