Lesson_4_level_1-4
antdolg1/jg_java_1_monday_june_2022 pull request #44
Opened 2022-07-13 11:31 UTC by AlisaSin

2022-07-15 16:44 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/Lesson4.java
> +        System.out.println("number is less than 20");
Would this statement _"number is less than 20"_ be valid if user inputs 20?

2022-07-15 17:01 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +        }
Please format lines.

2022-07-15 17:01 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +            return "numbers are equals";
equals --> equal

2022-07-15 17:04 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +            return secondNumber;
I think here `thirdNumber` should be returned.

2022-07-15 17:10 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +                return secondNumber;
You return this when all numbers are equal, am I right? If yes, than I would propose to replace this `else` with `else if` `(firstNumber == secondNumber && secondNumber == thirdNumber)` as it is would be easier to understand for others who would read you code.

2022-07-15 17:11 UTC, antdolg1 requested changes
Overall good job. Please check few comments and make adjustments.

2022-07-16 17:39 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +            return "numbers are equals";
я исправила все что вы написали и запушила. Посмотрите пожалуйста видите ли вы мои изменения.
В классе CalculatorTest у меня 2 теста fail, можете объяснить в чем ошибка?

2022-07-17 11:50 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
>          }
In this else if you have no return statement, please fix this.

2022-07-17 11:57 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/Lesson4.java
> +        System.out.println("number is less than 20");
Would this statement be valid if I enter number 20?

2022-07-17 12:01 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/CalculatorTest.java
> +        if (realResult == expectedResult) {
Strings should be compared using `equals()`

2022-07-17 12:02 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/CalculatorTest.java
> +        Boolean realResult = calculator.isEven(number);
Please use primitive type `boolean` instead of `Boolean`.

2022-07-17 12:03 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_5/LightColorDetectorTest.java
> +        if (realResult == expectedResult) {
Strings should be compared using equals()

2022-07-17 12:03 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_5/LightColorDetectorTest.java
> +        if (realResult == expectedResult) {
Strings should be compared using equals()

2022-07-17 12:04 UTC, antdolg1 requested changes
Please take a look at comments.

2022-07-17 12:04 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_5/LightColorDetectorTest.java
> +        if (realResult == expectedResult) {
Strings should be compared using `equals()`

2022-07-17 12:04 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_5/LightColorDetectorTest.java
> +        if (realResult == expectedResult) {
Strings should be compared using `equals()`

2022-07-17 12:04 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_5/LightColorDetectorTest.java
> +        if (realResult == expectedResult) {
Strings should be compared using `equals()`

2022-07-17 12:04 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_5/LightColorDetectorTest.java
> +        if (realResult == expectedResult) {
Strings should be compared using `equals()`

2022-07-17 12:04 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_5/LightColorDetectorTest.java
> +        if (realResult == expectedResult) {
Strings should be compared using `equals()`

2022-07-17 12:15 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
>          }
у меня так работает. А если я ставлю скобку после return, то показыватся ошибка java: missing return statement. Я проверила все скобки, все остальное верное, мне IDEA сама предложила так исправить :(

2022-07-17 14:42 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
>          }
```
else if (secondNumber == firstNumber && firstNumber == thirdNumber) {
         return firstNumber;
        }
```

Otherwise your last `else if `statement has no code to execute.

2022-07-17 14:43 UTC, antdolg1 requested changes
Please check my comment.

*Also after you apply fixes please re-request review so I could see it.

2022-07-21 17:46 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +        return -100500;
я должна вывести в других случаях значение int, но я не придумала как еще оформить это

2022-07-22 15:03 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +        return -100500;
Can you provide example when -100500 would be returned? What is the case for this?

2022-07-22 15:03 UTC, antdolg1 requested changes
Please check my comment.

2022-07-22 17:48 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +        return -100500;
мне кажется я охватила все варианты в if и else if, но без окончательного else мой код не работает. Поэтому мне надо написать else, и я написала просто случайно выбранное число. Если вдруг есть вариант который я не учла то пользователю покажется -100500 и будет понятно что что то введено не так

2022-07-24 12:38 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +        return -100500;
I would suggest to double check if all cases are covered and wrap last case in `else` instead of `else if`, that would be the best solution in this case because you know all possible cases and you won't need to return random number.

2022-07-26 11:49 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/lesson_4/homework/level_4/Calculator.java
> +        return -100500;
то есть вместо последнего else if когда все числа равны я должна сделать просто else? Просто именно так я и выполнила задание, а вы попросили оформить это условие через else if и после этого у меня начались проблемы

2022-07-29 12:31 UTC, antdolg1 approved these changes

2022-07-29 12:31 UTC, merged