St robert pavlov lesson 4
antdolg1/jg_java_1_monday_june_2022 pull request #51
Opened 2022-07-17 10:27 UTC by roberts-pavlovs

2022-07-17 14:25 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_1/Lesson_4_Level_1_Task_1.java
> +            System.out.println("TRUE");
Output message does not contain any meaningful for the user info. Please fix.

2022-07-17 14:26 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_1/Lesson_4_Level_1_Task_2.java
> +}
This is not what was required in Lesson_4 Task_2. Please fix.

2022-07-17 14:27 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_1/Lesson_4_Level_1_Task_3.java
> +        } else if (day == 8) {
`day == 8` --> `day == 7`

2022-07-17 14:28 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_1/Lesson_4_Level_1_Task_4.java
> +    }
Please fix formatting.

2022-07-17 14:36 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_2/Lesson_4_Level_2_Task_7.java
> +        else if ((x == y) || (x == z) || (z == y))
Why do we need this `else if` statement if this statement is not reachable?

2022-07-17 14:38 UTC, antdolg1 requested changes
Please check comments.

P.S. Please include in PR changes only related to the level. For example you named this branch level-4 but it contains homework from lesson 1, lesson 2 and lesson 3.

2022-07-24 18:43 UTC, roberts-pavlovs commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_1/Lesson_4_Level_1_Task_4.java
> +    }
Can't find error

2022-07-24 18:44 UTC, roberts-pavlovs commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_2/Lesson_4_Level_2_Task_7.java
> +        else if ((x == y) || (x == z) || (z == y))
We don't need it, fixed the bug.

2022-07-24 20:55 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_1/Lesson_4_Level_1_Task_4.java
> +    }
Just press `Ctrl+Alt+L` and Intellij IDEA will apply auto format.

2022-07-24 20:56 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_3/Level_1/Lesson_4_Level_1_Task_3.java
> +        if (day == 5) {
`if (day == 5)` --> `if (day == 1)`

2022-07-24 20:57 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_3/Level_1/Lesson_4_Level_1_Task_4.java
> +}
Please auto format the code `Ctrl+Alt+L`

2022-07-24 20:59 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_3/Level_1/Lesson_4_Level_1_Task_3.java
> +        int day = 7;
We should read this value from user input via scanner.

2022-07-24 21:04 UTC, antdolg1 commented on src/main/java/teacher/students/student_robert_pavlov/lesson_2/PrimitiveVariables.java
> +}
Please remove this file from teacher folder.

2022-07-24 21:08 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_2/Lesson_4_Level_2_Task_7.java
> +        int z = in.nextInt();
In Lesson 4 Level 2 Task 7 it is required from user to input only 2 numbers, not 3. Please fix according to task requirements.

2022-07-24 21:08 UTC, antdolg1 requested changes
Some issues are fixed, some not. Please check new comments.

2022-07-28 13:56 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_4/Level_1/Level_2/Lesson_4_Level_2_Task_7.java
> +        } else if ((x != y)) {
1. No need for double `(( ))`
2. Actually no need for this check at all, you can safely replace it with `else`

2022-08-21 12:35 UTC, antdolg1 approved these changes

2022-08-21 12:35 UTC, merged