Homework_task_8-10
antdolg1/jg_java_1_monday_june_2022 pull request #58
Opened 2022-07-24 09:33 UTC by DenissKaira

2022-07-24 21:15 UTC, antdolg1 commented on src/main/java/students/student_Denis_Kaira/Lesson_4/Homework/Task8.java
> +            } else if (number != number2 && number2 != number && number3 != number) {
`number != number2` and `number2 != number` is the same one of them can be removed.

2022-07-24 21:20 UTC, antdolg1 commented on src/main/java/students/student_Denis_Kaira/Lesson_4/Homework/Task10.java
> +            System.out.print("number3 is biggest ");
None of this statements is 100% true because you use `>=` instead of `>`. So if user enters three same numbers your program will show that **_number is the biggest_** but should show that numbers are equal.

2022-07-24 21:20 UTC, antdolg1 requested changes
Please check my comments, there are few things needs to be fixed. After you fix them please re-request the review.

2022-08-01 21:51 UTC, antdolg1 commented on src/main/java/students/student_Denis_Kaira/Lesson_4/Homework/Task8.java
> +            } else if (number != number2 && number2 != number && number3 != number) {
Please remove one of the statements as they are the same.

2022-08-01 21:51 UTC, antdolg1 requested changes
Please check my comment regarding Task_8.

2022-08-21 21:41 UTC, antdolg1 commented on src/main/java/students/student_Denis_Kaira/Lesson_4/Homework/Task8.java
> +            } else if (number == number2 || number == number3 || number2 == number3) {
Why did you change the else if condition from comparing if numbers are not equal to comparing if numbers are equal? All you needed to do to remove `number2 != number`, because `number2 != number` and `number != number2` is the same.

2022-08-21 21:42 UTC, antdolg1 requested changes
Please read my new and previous comments carefully and apply the fixes according to them.

2022-08-22 13:48 UTC, DenissKaira commented on src/main/java/students/student_Denis_Kaira/Lesson_4/Homework/Task8.java
> +            } else if (number == number2 || number == number3 || number2 == number3) {
perezalil.sravnil vse cisla na to cto oni ne ravni.vrode tak ponjal

2022-08-23 07:52 UTC, antdolg1 approved these changes

2022-08-23 07:52 UTC, merged