St robert pavlov lesson 5
antdolg1/jg_java_1_monday_june_2022 pull request #63
Opened 2022-07-27 20:58 UTC by roberts-pavlovs

2022-07-29 12:48 UTC, antdolg1 reviewed
Please first of all remove all files which are not related to lesson 5 homeworks.

2022-07-29 12:51 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/level_1/Task_5.java
> +            int [] numbers = {1, 2, 3,};
Please remove last comma (after number 3)

2022-07-29 12:55 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/Task_2/Task_12.java
> +        numbers[2] = (int) (Math.random() * (10-7)) + 5;
To get random number I would suggest to use Random library. Example:

```
        Random random = new Random();
        int randomNumber = random.nextInt();
```

2022-07-29 12:56 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/Task_2/Task_13.java
> +        numbers[2] = (int) (Math.random() * (10-7)) + 5;
Same comment as in Task_12.

2022-07-29 12:58 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/Task_2/Task_15.java
> +        Scanner scanner = new Scanner(System.in);
Unused scanner, please remove.

2022-07-29 12:59 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/Task_2/Task_15.java
> +        numbers[0] = numbers[0]++;
This would increase value by 1, not by 2 as it was requested in homework.
Hint:
`numbers[0] += 2;`

2022-07-29 13:00 UTC, antdolg1 requested changes
Overall very good job. Please fix few issues I mentioned in comments.

2022-07-31 22:17 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/Task_2/Task_12.java
> +        int randomNumber = random.nextInt();
Let's take a look at your code. You create new Random object - that's good, you create random variable `randomNumber` and assign random number to it - okay, but after you do not use it anywhere. My idea was that you should replace `(int) (Math.random() * (10-5)) + 5` etc. with `random.nextInt()`. So remember, if you want to create some random number, use `random.nextInt()`. Please fix this in all tasks where you create random number in a wrong way.

2022-07-31 22:22 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/Task_2/Task_15.java
> +        numbers[2] += numbers[2];
Have you tried to run your code? Does it increase each number by 2?

2022-07-31 22:23 UTC, antdolg1 requested changes
Please check comments, still have things to fix.

2022-08-02 19:20 UTC, roberts-pavlovs commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/Task_2/Task_12.java
> +        int randomNumber = random.nextInt();
Исправил ошибки

2022-08-02 20:32 UTC, antdolg1 commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/Task_2/Task_15.java
> +        System.out.println (("Incremented value of cell number 1: " + numbers[0] +2) + "! "  + " Incremented value of cell number 1: " +  (numbers[1] +2) + "! " + " Incremented value of cell number 1
Still need to fix Task_15. The requirement was to increment each element of array by 2 and save it in array. Actually in the beginning you were pretty close to the solution, just need to adjust it little bit.

```
numbers[0] += numbers[0];  ---> numbers[0] = numbers[0] + 2;
numbers[1] += numbers[1];  ---> numbers[1] = numbers[0] + 2;
numbers[2] += numbers[2];  ---> numbers[2] = numbers[0] + 2;
```

2022-08-02 20:34 UTC, antdolg1 requested changes
Small adjustment needed in Task_15. Please check comment.

2022-08-03 18:17 UTC, roberts-pavlovs commented on src/main/java/students/student_robert_pavlov/homework/lesson_5/Task_2/Task_15.java
> +        System.out.println (("Incremented value of cell number 1: " + numbers[0] +2) + "! "  + " Incremented value of cell number 1: " +  (numbers[1] +2) + "! " + " Incremented value of cell number 1
now its ok?

2022-08-11 07:23 UTC, antdolg1 approved these changes

2022-08-11 07:23 UTC, merged