St martin valba lesson 5 level 1 2
antdolg1/jg_java_1_monday_june_2022 pull request #65
Opened 2022-07-29 19:31 UTC by pecoyn

2022-08-01 22:29 UTC, antdolg1 commented on src/main/java/students/student_Martin_Valba/lesson_5/homework/level_2/Task12.java
> +        number[2] = thirdRandom;
In this case array will be filled with three equal numbers. If you want to fill it with different numbers, you need to call `random.nextInt()` every time. E.g.

```
      int firstRandom = random.nextInt();
      int secondRandom = random.nextInt();
      int thirdRandom = random.nextInt();
```

2022-08-01 22:30 UTC, antdolg1 commented on src/main/java/students/student_Martin_Valba/lesson_5/homework/level_2/Task13.java
> +        int[] randoms = {randomNumber, randomNumber, randomNumber};
Same issue as in task 12.

2022-08-01 22:30 UTC, antdolg1 commented on src/main/java/students/student_Martin_Valba/lesson_5/homework/level_2/Task14.java
> +        int[] randoms = {randomNumber, randomNumber, randomNumber};
Same issue as in task 12.

2022-08-01 22:31 UTC, antdolg1 requested changes
Please check my comments regarding generating random number and apply fixed. Other than that - good job!

2022-08-09 13:27 UTC, pecoyn commented on src/main/java/students/student_Martin_Valba/lesson_5/homework/level_2/Task12.java
> +        number[2] = thirdRandom;
Done

2022-08-09 13:27 UTC, pecoyn commented on src/main/java/students/student_Martin_Valba/lesson_5/homework/level_2/Task13.java
> +        int[] randoms = {randomNumber, randomNumber, randomNumber};
Done

2022-08-09 13:27 UTC, pecoyn commented on src/main/java/students/student_Martin_Valba/lesson_5/homework/level_2/Task14.java
> +        int[] randoms = {randomNumber, randomNumber, randomNumber};
Done

2022-08-21 10:33 UTC, antdolg1 approved these changes

2022-08-21 10:33 UTC, merged