Commit 5l
antdolg1/jg_java_1_monday_june_2022 pull request #66
Opened 2022-07-29 22:40 UTC by M4488

Finished  1 - 2 lessons. I'll try to finish other lessons later.

2022-08-01 22:37 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/lesson_5_homeworks/level_2/Task_12.java
> +        System.out.println("1 Random number: " + Math.random());
1. You are not filling array with random numbers.
2. Math.random() will generate double, not int. To generate random int please use:
```
Random random = new Random();
random.nextInt();
```

2022-08-01 22:39 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/lesson_5_homeworks/level_2/Task_13.java
> +
No need for two loops, all could be done in one:

```
    public static void main(String[] args) {
        int[] array = new int[3];
        for (int i = 0; i < array.length; i++) {
            array[i] = (int) (Math.random() * 10); // случайное число до 10
            System.out.println(array[i]);
        }
        System.out.println("Sum = " + (array[0] + array[1] + array[2]));
    }
```

2022-08-01 22:41 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/lesson_5_homeworks/level_2/Task_14.java
> +                                                     //оставлять ли эту строку пустой, пробелом для красоты?
Yes, it is good idea to insert empty line. It is easier to read the code.

2022-08-01 22:41 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/lesson_5_homeworks/level_2/Task_14.java
> +                                                     //оставлять ли эту строку пустой, пробелом для красоты?
Same comment as in Task_13, no need for two loops.

2022-08-01 22:43 UTC, antdolg1 requested changes
Overall very good! Please check my comments, make adjustments and re-request review for your PR.

2022-08-01 23:25 UTC, M4488 reviewed
Учусь использовать переписку.
comment  видимо можно написать коментарий
Approve -  это видимо для професионалов
Request changes -  это видимо для професионалов

2022-08-01 23:28 UTC, M4488 commented
Не понимаю что нужно нажать, чтобы в гит хабе было видно, что я исправил и отправил повторно.

2022-08-02 08:23 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/lesson_5_homeworks/level_2/Task_12.java
> +        numbers[2] = (int) random.nextInt();   // поменял
Casting to **int** is not needed in this case because r`andom.nextInt()` returns **int**. Please remove `(int)` on line 11, 12, 13.

2022-08-02 08:26 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/lesson_5_homeworks/level_2/Task_13.java
> +            array[i] = (int) (Math.random() * 10);
Not it looks better but you remover array output to console - `System.out.println(array[i]);`. Please bring it back.

2022-08-02 08:28 UTC, antdolg1 requested changes
Please check my comments and apply changes accordingly to them. After re-request review.

2022-08-02 20:26 UTC, antdolg1 approved these changes
Now all is good! Solid effort!

2022-08-02 20:26 UTC, merged