St maksim turcin 2 level 1 task 1
antdolg1/jg_java_1_monday_june_2022 pull request #7
Opened 2022-06-28 23:03 UTC by M4488

Create pull request

2022-07-01 08:50 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_0_beginner/CeljOnZheTArget.java
> +
Redundant empty line.

2022-07-01 08:52 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_1_intern/ScannerProgram.java
> +        int secondNumber = scannerInput.nextInt();
Не хватает сообщения о том, что нужно ввести вторую цифру. Это может запутать пользователя вашей программы.

2022-07-01 08:56 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_1_intern/ScannerProgram.java
> +        System.out.println(" + = " + firstNumber + secondNumber);
Не совсем понятный текст перед выводом результата. Я бы рекомендовал что-то на подобии:
```
        int sum = firstNumber + secondNumber;
        System.out.println(firstNumber + " + " + secondNumber + " = " + sum);
```
И так далее.

2022-07-01 08:58 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_1_intern/ScannerProgram2.java
> +
Тут те же недочёты что и в ScannerProgram.java

2022-07-01 08:58 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_1_intern/ScannerProgram2.java
> +
Тут те же недочёты что и в ScannerProgram.java

2022-07-01 08:59 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_2_intern/BankAccount.java
> +
Лишние пустые строчки.

2022-07-01 09:00 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_2_intern/Book.java
> +// public static void main(String[] args) {    это видимо не нужно писать в задании??? или всё таки нужно
Функционал класса писать не надо. Тут всё верно. Только уберите лишние пустые строчки.

2022-07-01 09:05 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_3_junior/MiddleArithmetic.java
> +        Scanner scnNumber = new Scanner(System.in);
Не совсем удачное название для переменной, достаточно её назвать "scanner".

2022-07-01 09:06 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_3_junior/MiddleArithmetic.java
> +        System.out.println("Enter three numbers ");
Я бы рекомендовал перед вводом каждого числа вывести текст, чтобы пользователю было проще.
```
    System.out.print("Please, enter 1st number: ");
    ...
    System.out.print("Please, enter 1st number: ");
    ...
```

2022-07-01 09:17 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/Lesson_2_homeworks/level_3_junior/RingOfTheLord.java
> +            double perimeter = radius * 2 * 3.1415;
Всё верно. Если вы хотите получить математически более верный результат, то в качестве π можно использовать константу из библиотеки Math - `Math.PI`. Об этом я расскажу на следующей лекции при разборе домашек.

2022-07-01 09:18 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/lessonExercises/Test/PullRequest.java
> +public class PullRequest {
Давайте впредь не будем называть класс таким названием.

2022-07-01 09:19 UTC, antdolg1 commented on src/main/java/students/student_maksim_turcin/lessonExercises/Test/PullRequest.java
> +public class PullRequest {
Давайте впредь не будем называть класс таким названием.

2022-07-01 09:19 UTC, antdolg1 requested changes
Добавил комментарии по заданиям. 
Для чего вам пустой класс FunClass?

2022-07-03 01:10 UTC, M4488 commented
Uchusj poljzovatjsja Githubom

2022-07-03 01:10 UTC, closed without merging