St victor goloschapov lesson 2 level 1 task 1
antdolg1/jg_java_1_monday_june_2022 pull request #8
Opened 2022-06-30 09:29 UTC by VictorGoloschapov

Good day!
Kindly asking to review Task_1.

2022-07-01 09:25 UTC, antdolg1 requested changes
Добавил комментарии по заданию.

2022-07-01 16:56 UTC, VictorGoloschapov commented on src/main/java/students/student_Victor_Goloschapov/Lesson_2_homeworks/level_1/SimpleCalculator1.java
> +public class SimpleCalculator1 {
Поменял название класса на Task1 и перезалил в репозиторий

2022-07-01 16:58 UTC, VictorGoloschapov commented on src/main/java/students/student_Victor_Goloschapov/Lesson_2_homeworks/level_1/SimpleCalculator1.java
> +            multResult;
В рамках данных учебных допустимо (стилистически) ли так инициализировать переменные (списком), если они одного типа?

2022-07-02 16:00 UTC, antdolg1 commented on src/main/java/students/student_Victor_Goloschapov/Lesson_2_homeworks/level_1/SimpleCalculator1.java
> +            multResult;
Это не ошибка, задания будут засчитываться, но я бы просто рекомендовал всё таки каждую переменную объявлять отдельно. Стилистически так принято.

2022-07-02 16:01 UTC, antdolg1 approved these changes
Всё хорошо

2022-07-02 16:01 UTC, merged