St victor goloschapov lesson 8
antdolg1/jg_java_1_monday_june_2022 pull request #86
Opened 2022-08-15 10:42 UTC by VictorGoloschapov

Good day,
please review tasks from lesson 8, level 1, 2

2022-09-13 19:48 UTC, antdolg1 requested changes
Why you have so many duplicated Trader and Transaction classes? You can remove them, in the end to solve level 1 and level 2 your file structure should consist of:
1. Trader class
2. Transaction class
3. FraudDetector class
4. FraudDetectorTest class

Overall only 4 files. Please remove redundant copies.

2022-09-13 19:53 UTC, antdolg1 commented on src/main/java/students/student_Victor_Goloschapov/lesson_8/homework/level_2/Task_8/FraudDetector.java
> +        return transaction.getTrader().getFullName().equals(fraudName);
Good job on returning result of equals without if-else block. Here you might get NullPointerException if getTrader() or getTrader().getFullName() would return null, to avoid it call equals method on object which 100% are not null. So in this particular case simply swap places:
`transaction.getTrader().getFullName().equals(fraudName) --> fraudName.equals(transaction.getTrader().getFullName())`

2022-09-16 12:00 UTC, VictorGoloschapov commented on src/main/java/students/student_Victor_Goloschapov/lesson_8/homework/level_2/Task_8/FraudDetector.java
> +    }
made changes in equals() method as per Your recommendation.

2022-09-16 12:13 UTC, VictorGoloschapov commented
> 

I have removed redundant copies. Please advise if all is ok and according to task requirements?

2022-09-25 19:46 UTC, antdolg1 approved these changes

2022-09-25 19:46 UTC, merged