Lesson_8_level_1-2
antdolg1/jg_java_1_monday_june_2022 pull request #88
Opened 2022-08-17 18:53 UTC by AlisaSin

2022-09-13 19:59 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_8/level1_2/FraudDetector.java
> +        return tr.getFullName().equals("Pokemon");
Use `fName` `return fName.equals("Pokemon")` or remove assigment of `fName`.

Also here the is a risk to get NullPointerException if Trader would be null or if tr.getFullName() would be null. To avoid it please call equals method on objects which are 100% not null. So in our case compliant solution would be:
`"Pokemon".equals(fName) `

2022-09-13 20:01 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_8/level1_2/Trader.java
> +
No need for setters. Can be removed.

2022-09-13 20:01 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_8/level1_2/FraudDetectorTest.java
> +}
Good job on tests!

2022-09-13 20:02 UTC, antdolg1 requested changes
Good job on tests! Please check my comments, some small changes are needed.

2022-09-25 06:45 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/lesson_8/level1_2/FraudDetector.java
> +        return tr.getFullName().equals("Pokemon");
thanks

2022-09-25 06:46 UTC, AlisaSin commented on src/main/java/students/student_Alisa_Sinavska/lesson_8/level1_2/Trader.java
> +
ok

2022-09-25 19:51 UTC, antdolg1 commented on src/main/java/students/student_Alisa_Sinavska/lesson_8/level1_2/FraudDetector.java
> +        return tr.getFullName().equals(fName);
By this change you are comparing string tr.getFullName to itself, which makes no sense. You need to compare it with "Pokemon" and to avoid potential NullPointerException call equals method from "Pokemon", not vice verse. Please check my previous comment: https://github.com/antdolg1/jg_java_1_monday_june_2022/pull/88#discussion_r970032698

2022-09-25 19:52 UTC, antdolg1 requested changes
Please check my comment for FraudDetector class and apply small changes. If you have any problems with it, let me know, we can take a look at this case during the next lesson.

2022-10-02 19:19 UTC, antdolg1 approved these changes

2022-10-02 19:19 UTC, merged