St victor goloschapov lesson 11
antdolg1/jg_java_1_monday_june_2022 pull request #99
Opened 2022-09-20 11:39 UTC by VictorGoloschapov

Good day,

Please review tasks from lesson 11, level 1 - 2.

2022-12-21 22:47 UTC, antdolg1 commented on src/main/java/students/student_Victor_Goloschapov/lesson_11/homework/level_2/Task_6/BookDatabaseImpl.java
> +        book.setId((long) bookList.size());
Не совсем верно реализована логика присвоения уникального ID для книги, так как если ты удалишь из списка книгу и потом добавишь, то у тебя может быть ситуация, что в списке будет две книги с одинаковым ID.

Я бы рекомендовал создать глобальную переменную:
`private Long currentId = 1L;`

И потом в методе save() присваешь её в качестве ID книги, после увеличиваешь и возвращаешь.

2022-12-21 22:53 UTC, antdolg1 commented on src/main/java/students/student_Victor_Goloschapov/lesson_11/homework/level_2/Task_8/BookDatabaseImpl.java
> +        for (Book books : bookList) {
Название переменной должно быть в единственном числе, и лучше поменяй его, чтобы у тебя не было такого:

`book.equals(book)`

2022-12-21 22:57 UTC, antdolg1 commented on src/main/java/students/student_Victor_Goloschapov/lesson_11/homework/level_2/Task_10/BookDatabaseImpl.java
> +            if (bookList.get(i).getAuthor().equals(author)) {
Для избежания потенциального NPE поменяй местами:
`(bookList.get(i).getAuthor().equals(author))` --> `(author.equals(bookList.get(i).getAuthor()))`

2022-12-21 22:58 UTC, antdolg1 requested changes
В целом очень даже неплохо, просто и понятно, но есть пару моментов. Посмотри мои комментарии.

2022-12-22 10:00 UTC, VictorGoloschapov commented on src/main/java/students/student_Victor_Goloschapov/lesson_11/homework/level_2/Task_6/BookDatabaseImpl.java
> +        book.setId((long) bookList.size());
В классе Book уже есть переменная id. А если мне в классе BookDatabaseImpl как Вы рекомендовали объявить переменную private Long currentId, но не сразу присваивать значение 1. Вызвать метод setId() из класса Book, а потом присвоить значение переменной currentId  с помощью метода getId(). Я тогда использую все поля класса Book.

Примерно так:

private Long currentId;

private Long initializeId(Book book) {
   book.setId(1L);
   currentId = book.getId();
   return currentId;
}

В методе save() я смогу использовать метод initializeId() как вспомогательный.

Это просто идея, не тестировал в коде :)

2022-12-22 10:13 UTC, VictorGoloschapov commented on src/main/java/students/student_Victor_Goloschapov/lesson_11/homework/level_2/Task_6/BookDatabaseImpl.java
> +        book.setId((long) bookList.size());
Есть у меня вопрос по объекту-обертке Long. С такими объектами можно делать арифмитические операции. Но желательно ли с начала из объекта Long распаковавать примитивное значение long и потом делать арифметику?
Как лучше?

2022-12-24 17:54 UTC, VictorGoloschapov commented on src/main/java/students/student_Victor_Goloschapov/lesson_11/homework/level_2/Task_10/BookDatabaseImpl.java
> +            if (bookList.get(i).getAuthor().equals(author)) {
Все моменты исправил

2022-12-27 19:48 UTC, antdolg1 approved these changes

2022-12-27 19:48 UTC, merged